version: '3.9'

services:
  db:
    user: postgres
    restart: always
    build: .
    container_name: db
    networks:
      - djangonetwork
      - postgres
    image: postgres:alpine
    ports:
        - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - LC_ALL=C.UTF-8
      - POSTGRES_DB= data_my_api
      - POSTGRES_USER= postgres
      - POSTGRES_PASSWORD= 123456
      - POSTGRES_HOST_AUTH_METHOD=trust
  
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    volumes:
      - pgadmin:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - 5050:80
    networks:
      - postgres
      
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    links:
      - db:db
    networks:
      - djangonetwork

networks:
  djangonetwork:
      driver: bridge
  postgres:

volumes:
  pgdata:
  pgadmin:

